// lib/decompose/country-aliases.ts

export const COUNTRY_ALIASES: Record<string, string> = {
  "South Korea": "South Korea",
  "Republic of Korea": "South Korea",
  "Korea": "South Korea",
  "USA": "United States",
  "US": "United States",
  "U.S.": "United States",
  "U.S.A.": "United States",
  "America": "United States",
  "UK": "United Kingdom",
  "Britain": "United Kingdom",
  "Great Britain": "United Kingdom",
  "England": "United Kingdom",
  "DRC": "Congo",
  "DR Congo": "Congo",
  "Democratic Republic of the Congo": "Congo",
  "Congo, Democratic Republic of": "Congo",
  "Congo-Kinshasa": "Congo",
  "Republic of China": "Taiwan",
  "Chinese Taipei": "Taiwan",
  "ROC": "Taiwan",
  "People's Republic of China": "China",
  "PRC": "China",
  "Mainland China": "China",
  "Russia": "Russia",
  "Russian Federation": "Russia",
  "Vietnam": "Vietnam",
  "Viet Nam": "Vietnam",
  "Iran": "Iran",
  "Islamic Republic of Iran": "Iran",
  "Czech Republic": "Czechia",
  "Czech": "Czechia",
  "UAE": "United Arab Emirates",
  "UAR": "United Arab Emirates",
  "Emirates": "United Arab Emirates",
  "Republic of India": "India",
  "Federal Republic of Germany": "Germany",
  "Kingdom of Saudi Arabia": "Saudi Arabia",
  "KSA": "Saudi Arabia",
  "Republic of Turkey": "Turkey",
  "Türkiye": "Turkey",
  "Republic of Indonesia": "Indonesia",
  "Federative Republic of Brazil": "Brazil",
  "Commonwealth of Australia": "Australia",
  "Kingdom of Thailand": "Thailand",
  "Republic of Kazakhstan": "Kazakhstan",
  "Republic of Zambia": "Zambia",
  "Burma": "Myanmar",
  "Myanmar": "Myanmar",
  "Republic of the Union of Myanmar": "Myanmar",
  "Democratic Republic of Sudan": "Sudan",
  "Republic of the Sudan": "Sudan",
  "Republic of the Philippines": "Philippines",
  "Republic of Kenya": "Kenya",
  "United Republic of Tanzania": "Tanzania",
  "Republic of Ghana": "Ghana",
  "Republic of Namibia": "Namibia",
  "Republic of Angola": "Angola",
  "Republic of Zimbabwe": "Zimbabwe",
  "Kingdom of Morocco": "Morocco",
  "Republic of Peru": "Peru",
  "Republic of Chile": "Chile",
  "Republic of Argentina": "Argentina",
  "Republic of Colombia": "Colombia",
  "Kingdom of the Netherlands": "Netherlands",
  "Holland": "Netherlands",
  "Republic of Poland": "Poland",
  "Republic of South Africa": "South Africa",
  "Slovak Republic": "Slovakia",
  "Slovakia": "Slovakia",
  "Republic of Singapore": "Singapore",
  "Federation of Malaysia": "Malaysia",
  "State of Japan": "Japan",
  "Republic of France": "France",
  "Italian Republic": "Italy",
  "Kingdom of Spain": "Spain",
  "United Mexican States": "Mexico",
  "Republic of South Sudan": "South Sudan",
};

export function normalizeCountryName(name: string): string {
  return COUNTRY_ALIASES[name] ?? name;
}
