// lib/decompose/country-aliases.ts

export const COUNTRY_ALIASES: Record<string, string> = {
  "South Korea": "South Korea",
  "Republic of Korea": "South Korea",
  "Korea": "South Korea",
  "USA": "United States",
  "US": "United States",
  "U.S.": "United States",
  "U.S.A.": "United States",
  "America": "United States",
  "UK": "United Kingdom",
  "Britain": "United Kingdom",
  "Great Britain": "United Kingdom",
  "England": "United Kingdom",
  "DRC": "Congo",
  "DR Congo": "Congo",
  "Democratic Republic of the Congo": "Congo",
  "Democratic Republic of Congo": "Congo",
  "Congo, Democratic Republic of": "Congo",
  "Congo (DRC)": "Congo",
  "Republic of China": "Taiwan",
  "Chinese Taipei": "Taiwan",
  "ROC": "Taiwan",
  "People's Republic of China": "China",
  "PRC": "China",
  "Mainland China": "China",
  "Russia": "Russia",
  "Russian Federation": "Russia",
  "Vietnam": "Vietnam",
  "Viet Nam": "Vietnam",
  "Iran": "Iran",
  "Islamic Republic of Iran": "Iran",
  "Czech Republic": "Czechia",
  "UAE": "United Arab Emirates",
  "UAR": "United Arab Emirates",
  "Emirates": "United Arab Emirates",
  "Republic of India": "India",
  "Federal Republic of Germany": "Germany",
  "Kingdom of Saudi Arabia": "Saudi Arabia",
  "KSA": "Saudi Arabia",
  "Republic of Turkey": "Turkey",
  "Türkiye": "Turkey",
  "Republic of Indonesia": "Indonesia",
  "Federative Republic of Brazil": "Brazil",
  "Commonwealth of Australia": "Australia",
  "Kingdom of Thailand": "Thailand",
  "Republic of Kazakhstan": "Kazakhstan",
  "Republic of Zambia": "Zambia",
  "Republic of Zimbabwe": "Zimbabwe",
  "Kingdom of Morocco": "Morocco",
  "United Republic of Tanzania": "Tanzania",
  "Republic of Kenya": "Kenya",
  "Republic of Angola": "Angola",
  "Republic of Ghana": "Ghana",
  "Plurinational State of Bolivia": "Bolivia",
  "Republic of Colombia": "Colombia",
  "Republic of Namibia": "Namibia",
  "Republic of the Philippines": "Philippines",
  "Burma": "Myanmar",
};

export function normalizeCountryName(name: string): string {
  return COUNTRY_ALIASES[name] ?? name;
}
